easy_admin:
  entities:
  # List the entity class name you want to manage
    - App\Entity\Category
    - App\Entity\Faq
    - App\Entity\Intervention
    - App\Entity\News
    - App\Entity\Picture
    - App\Entity\prectitioner
    - App\Entity\User



parameters:
  app.path.product_images: /uploads/thumbnails
  # ...
